// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDccR1A8gkX3jaajC-FiUer4arJVejnXco',
    appId: '1:394601786656:web:78270c25b9c83c5701bb45',
    messagingSenderId: '394601786656',
    projectId: 'my-app-bc894',
    authDomain: 'my-app-bc894.firebaseapp.com',
    storageBucket: 'my-app-bc894.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7XFysKoF9rlpY3nGJ2dwqyvX5AP6gmFE',
    appId: '1:394601786656:android:e61c3f7a6622f25c01bb45',
    messagingSenderId: '394601786656',
    projectId: 'my-app-bc894',
    storageBucket: 'my-app-bc894.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIIvsNHDQTcvqHAYL4mu-Gw2nu2iW3lkk',
    appId: '1:394601786656:ios:a66a5f4738f0388b01bb45',
    messagingSenderId: '394601786656',
    projectId: 'my-app-bc894',
    storageBucket: 'my-app-bc894.firebasestorage.app',
    iosBundleId: 'com.exampal.my.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIIvsNHDQTcvqHAYL4mu-Gw2nu2iW3lkk',
    appId: '1:394601786656:ios:f4db9b8cabbf918301bb45',
    messagingSenderId: '394601786656',
    projectId: 'my-app-bc894',
    storageBucket: 'my-app-bc894.firebasestorage.app',
    iosBundleId: 'com.example.dummy.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDccR1A8gkX3jaajC-FiUer4arJVejnXco',
    appId: '1:394601786656:web:0daaf31c4b9a676d01bb45',
    messagingSenderId: '394601786656',
    projectId: 'my-app-bc894',
    authDomain: 'my-app-bc894.firebaseapp.com',
    storageBucket: 'my-app-bc894.firebasestorage.app',
  );

}